### ISSUE TITLE
Can we close it using browser back button?

### ISSUE THREAD

**Issue by anil1712** [popdevelop/angular-splash-demo#1]
Its really a good stuff with simple example and really useful for me. Everything is working fine but I need some enhancement.

Can we close the modal using back button? I got reviews from many of the users so they are trying to close it using back key. So it would be great if you can also add this feature in your repo.

**Comment by wallin** [comment]
Hi, sorry for a late reply. I believe that it is not the responsibility of this modal to handle back-behavior and/or routes. The best way of implementing this would be to open the modal when on the desired url/route. Then the back-behavior will come automatically.
